version: '3.8'
services:
  web:
    image: mediconnect:latest
    build: .
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: MediConnect
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: your-email@example.com
      PGADMIN_DEFAULT_PASSWORD: your-password
    ports:
      - "8080:80"
    depends_on:
      - db
volumes:
  postgres_data:
