"""Add is urgent

Revision ID: 07c7ef3e34ce
Revises: 4656ecb5bf43
Create Date: 2024-02-18 13:58:12.910297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07c7ef3e34ce'
down_revision: Union[str, None] = '4656ecb5bf43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultations', sa.Column('is_urgent', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'consultations', 'treatment_rooms', ['treatment_room_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'consultations', type_='foreignkey')
    op.drop_column('consultations', 'is_urgent')
    # ### end Alembic commands ###
