"""Treatment rooms update

Revision ID: 4656ecb5bf43
Revises: 495be8617e8e
Create Date: 2024-02-17 20:37:39.764467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4656ecb5bf43'
down_revision: Union[str, None] = '495be8617e8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('treatment_rooms', sa.Column('room_type', sa.String(), nullable=True))
    op.create_index(op.f('ix_treatment_rooms_room_type'), 'treatment_rooms', ['room_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_treatment_rooms_room_type'), table_name='treatment_rooms')
    op.drop_column('treatment_rooms', 'room_type')
    # ### end Alembic commands ###
