"""Rename maintenance_status to under_maintenance

Revision ID: 561adb0278dc
Revises: 07c7ef3e34ce
Create Date: 2024-02-19 21:56:20.254137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '561adb0278dc'
down_revision: Union[str, None] = '07c7ef3e34ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('treatment_machines', sa.Column('under_maintenance', sa.Boolean(), nullable=True))
    op.drop_column('treatment_machines', 'maintenance_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('treatment_machines', sa.Column('maintenance_status', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('treatment_machines', 'under_maintenance')
    # ### end Alembic commands ###
