"""Add doctor is_available

Revision ID: 730465a09dce
Revises: 0b7b6a99287c
Create Date: 2024-02-22 21:25:07.522462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '730465a09dce'
down_revision: Union[str, None] = '0b7b6a99287c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('is_available', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'is_available')
    # ### end Alembic commands ###
