"""Remove unique

Revision ID: f7db35c0eb79
Revises: 6621dc4c9708
Create Date: 2024-02-16 20:23:25.845809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7db35c0eb79'
down_revision: Union[str, None] = '6621dc4c9708'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('medical_histories_patient_id_key', 'medical_histories', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('medical_histories_patient_id_key', 'medical_histories', ['patient_id'])
    # ### end Alembic commands ###
